site_name: Eulen Platform Documentation
site_description: Documentación completa de la Plataforma Eulen
site_author: Team Eulen
repo_url: https://github.com/AngC1/Roadie
repo_name: AngC1/Roadie

theme:
  name: material
  palette:
    primary: indigo
    accent: indigo
  features:
    - navigation.tabs
    - navigation.sections
    - navigation.expand
    - search.suggest
    - search.highlight
    - content.code.copy
  icon:
    repo: fontawesome/brands/github

nav:
  - Inicio: index.md
  - Componentes:
      - Frontend Angular: frontend.md
      - API Node.js: api.md
      - Spring Boot Service: spring.md

markdown_extensions:
  - admonition
  - codehilite:
      linenums: true
  - toc:
      permalink: true
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.tasklist:
      custom_checkbox: true
  - attr_list
  - md_in_html

plugins:
  - search:
      lang: es
  - techdocs-core

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/AngC1/Roadie
  version:
    provider: mike
