# CD Pipeline for MCP Server - Azure Web App (sin secrets)
# Este workflow despliega el servidor MCP a Azure Web App usando variables directas (no recomendado para producción)

name: CD

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: 'Deploy to Azure Web App'
        uses: azure/webapps-deploy@v3
        with:
          app-name: TU_NOMBRE_WEBAPP
          publish-profile: |
            TU_CONTENIDO_PUBLISH_PROFILE_XML
          package: .
