name: Deploy to Roadie

on:
  workflow_dispatch:
  push:
    branches: [main]
    paths:
      - 'catalog/**'
      - 'catalog-info.yaml'
      - 'scaffolder-templates/**'
      - 'docs/**'
      - 'mkdocs.yml'

jobs:
  notify-catalog-update:
    name: Notify Catalog Update
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Catalog files changed
        run: |
          echo "Catalog files have been updated"
          echo "Roadie will automatically refresh the catalog from:"
          echo "https://github.com/AngC1/Roadie/blob/main/catalog-info.yaml"
          
      - name: List changed catalog files
        run: |
          echo "Changed files in this push:"
          git diff --name-only HEAD~1 HEAD | grep -E '(catalog/|catalog-info.yaml|scaffolder-templates/|docs/|mkdocs.yml)' || echo "No catalog files changed"

  validate-before-deploy:
    name: Validate Catalog Before Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Validate YAML files
        run: |
          pip install pyyaml
          echo "Validating catalog YAML files..."
          python -c "
          import yaml
          import sys
          from pathlib import Path
          
          errors = []
          catalog_files = list(Path('catalog').glob('*.yaml')) + [Path('catalog-info.yaml')]
          
          for file in catalog_files:
              if file.exists():
                  try:
                      with open(file) as f:
                          yaml.safe_load(f)
                      print(f'✓ {file}')
                  except Exception as e:
                      errors.append(f'{file}: {e}')
                      print(f'✗ {file}: {e}')
          
          if errors:
              print('\nValidation failed!')
              sys.exit(1)
          else:
              print('\nAll catalog files are valid!')
          "

  build-techdocs:
    name: Build TechDocs
    runs-on: ubuntu-latest
    if: contains(github.event.head_commit.modified, 'docs/') || contains(github.event.head_commit.modified, 'mkdocs.yml')
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install MkDocs
        run: |
          pip install mkdocs-techdocs-core

      - name: Build documentation
        run: |
          mkdocs build --strict
          
      - name: TechDocs built successfully
        run: |
          echo "TechDocs have been built successfully"
          echo "Roadie will serve them from the repository"
